#!/usr/bin/env python
# -*- coding: utf-8 -*-
print("Practicas Alumni - EducacionIT\n")

########### Ejercio 1 ############
# ~ i=0
# ~ while i < 10:
	# ~ i += 1
	# ~ print(i)
	
########### Ejercio 2 ############
while True:
	nombre = str(input("Ingrese su nombre: "))
	if nombre == "":
		print("Error!\nNo se ha ingresado un nombre.\n")
	else:
		print(f"\nMuchas gracias {nombre} por usar el programa")
		break
